### ISSUE TITLE
Migrate to hyper latest

### ISSUE THREAD

**Issue by 19h** [Byron/google-apis-rs#173]
Hey,

the new hyper release uses Futures and it fundamentally different to the former version. Is it possible to integrate support for hyper with futures without a rewrite?

**Comment by Byron** [comment]
Thanks for the suggestion, I had this thought too at some point, but discarded it for the time-being.

Even though I think it is possible, I don't expect it to be too easy. However, before investing the time needed to do that, I would clearly wait until hyper+futures+tokio(?) reached version 1.0.

**Comment by Idolf** [comment]
Given the current state of hyper, do you still feel like waiting for 1.0 is the right decision? We are currently considering using this library, but would strongly prefer using hyper 0.11 instead of hyper 0.10.

**Comment by Byron** [comment]
I just tried to build with hyper 0.11 and ran into a few build failures. They might be easy to fix, or not at all. In any case, there is the risk of having to redo similar work the next time it breaks, so I am very hesitant to invest time.
However, PRs are always welcome.

<details>

```
error[E0432]: unresolved import `hyper::header::HeaderFormat`
  --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:15:21
   |
15 |                     HeaderFormat, Bearer};
   |                     ^^^^^^^^^^^^ no `HeaderFormat` in `header`

error[E0433]: failed to resolve. Could not find `http` in `hyper`
  --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:16:12
   |
16 | use hyper::http::h1::LINE_ENDING;
   |            ^^^^ Could not find `http` in `hyper`

error[E0433]: failed to resolve. Could not find `net` in `hyper`
   --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:114:13
    |
114 | impl hyper::net::NetworkStream for DummyNetworkStream {
    |             ^^^ Could not find `net` in `hyper`

error[E0425]: cannot find value `LINE_ENDING` in this scope
   --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:436:49
    |
436 |                 (write!(&mut c, "{}--{}{}{}{}", LINE_ENDING, BOUNDARY, LINE_ENDING,
    |                                                 ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `LINE_ENDING` in this scope
   --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:436:72
    |
436 |                 (write!(&mut c, "{}--{}{}{}{}", LINE_ENDING, BOUNDARY, LINE_ENDING,
    |                                                                        ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `LINE_ENDING` in this scope
   --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:437:58
    |
437 |                                                 headers, LINE_ENDING)).unwrap();
    |                                                          ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `LINE_ENDING` in this scope
   --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:458:77
    |
458 |                                                         format!("{}--{}--", LINE_ENDING, BOUNDARY).into_bytes()))
    |                                                                             ^^^^^^^^^^^ not found in this scope

error[E0423]: expected function, found struct `UserAgent`
   --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:633:25
    |
633 |                 .header(UserAgent(self.user_agent.to_string()))
    |                         ^^^^^^^^^ did you mean `UserAgent { /* fields */ }`?

error[E0423]: expected function, found struct `UserAgent`
   --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:700:42
    |
700 |                                  .header(UserAgent(self.user_agent.to_string()))
    |                                          ^^^^^^^^^ did you mean `UserAgent { /* fields */ }`?

error[E0423]: expected function, found struct `UserAgent`
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1029:29
     |
1029 |                     .header(UserAgent(self.hub._user_agent.clone()))
     |                             ^^^^^^^^^ did you mean `UserAgent { /* fields */ }`?

error[E0423]: expected function, found struct `UserAgent`
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1354:29
     |
1354 |                     .header(UserAgent(self.hub._user_agent.clone()))
     |                             ^^^^^^^^^ did you mean `UserAgent { /* fields */ }`?

error[E0423]: expected function, found struct `UserAgent`
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1592:29
     |
1592 |                     .header(UserAgent(self.hub._user_agent.clone()))
     |                             ^^^^^^^^^ did you mean `UserAgent { /* fields */ }`?

error[E0423]: expected function, found struct `UserAgent`
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1827:29
     |
1827 |                     .header(UserAgent(self.hub._user_agent.clone()))
     |                             ^^^^^^^^^ did you mean `UserAgent { /* fields */ }`?

error[E0423]: expected function, found struct `UserAgent`
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2052:29
     |
2052 |                     .header(UserAgent(self.hub._user_agent.clone()))
     |                             ^^^^^^^^^ did you mean `UserAgent { /* fields */ }`?

error[E0423]: expected function, found struct `UserAgent`
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2295:29
     |
2295 |                     .header(UserAgent(self.hub._user_agent.clone()))
     |                             ^^^^^^^^^ did you mean `UserAgent { /* fields */ }`?

error[E0423]: expected function, found struct `UserAgent`
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2546:29
     |
2546 |                     .header(UserAgent(self.hub._user_agent.clone()))
     |                             ^^^^^^^^^ did you mean `UserAgent { /* fields */ }`?

error[E0423]: expected function, found struct `UserAgent`
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2810:29
     |
2810 |                     .header(UserAgent(self.hub._user_agent.clone()))
     |                             ^^^^^^^^^ did you mean `UserAgent { /* fields */ }`?

error[E0603]: module `method` is private
  --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:17:5
   |
17 | use hyper::method::Method;
   |     ^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `status` is private
  --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/cmn.rs:18:5
   |
18 | use hyper::status::StatusCode;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
   --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:960:45
    |
960 |                                http_method: hyper::method::Method::Get });
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1028:59
     |
1028 |                 let mut req = client.borrow_mut().request(hyper::method::Method::Get, &url)
     |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1295:45
     |
1295 |                                http_method: hyper::method::Method::Post });
     |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1353:59
     |
1353 |                 let mut req = client.borrow_mut().request(hyper::method::Method::Post, &url)
     |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1544:45
     |
1544 |                                http_method: hyper::method::Method::Get });
     |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1591:59
     |
1591 |                 let mut req = client.borrow_mut().request(hyper::method::Method::Get, &url)
     |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1780:45
     |
1780 |                                http_method: hyper::method::Method::Delete });
     |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:1826:59
     |
1826 |                 let mut req = client.borrow_mut().request(hyper::method::Method::Delete, &url)
     |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2005:45
     |
2005 |                                http_method: hyper::method::Method::Delete });
     |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2051:59
     |
2051 |                 let mut req = client.borrow_mut().request(hyper::method::Method::Delete, &url)
     |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2236:45
     |
2236 |                                http_method: hyper::method::Method::Post });
     |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2294:59
     |
2294 |                 let mut req = client.borrow_mut().request(hyper::method::Method::Post, &url)
     |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2490:45
     |
2490 |                                http_method: hyper::method::Method::Get });
     |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2545:59
     |
2545 |                 let mut req = client.borrow_mut().request(hyper::method::Method::Get, &url)
     |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2751:45
     |
2751 |                                http_method: hyper::method::Method::Put });
     |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `method` is private
    --> /Users/byron/dev/google-apis-rs/gen/youtubeanalytics1/src/lib.rs:2809:59
     |
2809 |                 let mut req = client.borrow_mut().request(hyper::method::Method::Put, &url)
     |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: cannot continue compilation due to previous error

error: Could not compile `google-youtubeanalytics1`.

To learn more, run the command again with --verbose.
make: *** [youtubeanalytics1-cli-cargo] Error 101
```

**Comment by bryanburgers** [comment]
Would it be valuable to document on the README that this does not work with the latest version of hyper, or especially which version of hyper to use?

I was trying to follow along with the initial example, and had a long period of confusion trying to match up the hyper API with the example, before I finally dove into the Cargo.toml to figure out which version of hyper and hyper-rustls I needed.

**Comment by Byron** [comment]
@bryanburgers Thanks for going through with it - your contribution was merged, and maybe I even get to re-release everything today.

**Comment by gyscos** [comment]
It might be easier to switch to [reqwest](https://crates.io/crates/reqwest), which wraps the client-side of `hyper` in an API closer to the pre-future version.

**Comment by paperplanes53** [comment]
Has anyone made a version of this crate using reqwest? If not, what is the process used with mako to regenerate the google-apis-rs code with every new hyper release (^0.9 to ^0.10 for example)?

**Comment by TheBiggerGuy** [comment]
I have nearly completed the work on migrating `yup-oauth2` to `hyper` v0.12. This project is tightly integrated with `google-apis-rs` so might be worth thinking about them together.

`yup-oauth2` does not fit the `reqwest` model as it does not directly support running as a HTTP server as well as a client. Naturally this could be solved by using two separate libraries however minimising the dependencies of `yup-oauth2` to a small set of widely used crates I believe is preferable.

On the `futures` API changes in  `hyper` I believe you can migrate to v0.12 without large changes in the code. The new API can be called in a synchronous was using `wait`.
```rust
let request = hyper::Request::post(uri)
    .header(header::CONTENT_TYPE, "application/x-www-form-urlencoded")
    .body(hyper::Body::from(body))?;
let response = self.client.request(request).wait()?;
```
A migration to the new `hyper` does not require a full rewrite to use async/futures in the sort or long term. After the migration some sections may be changed to be more inline the async/futures API but I belive it should be two separate issues 1) Moving to a maintained create 2) Potentially refactoring to async.

Please see https://github.com/dermesser/yup-oauth2/pull/86 for examples of the changes.

**Comment by paperplanes53** [comment]
@TheBiggerGuy Thank you for working on this.

**Comment by kiratp** [comment]
This library currently causes dependency conflicts if the codebase depends on tokio-rustls for its own use.

In our case, the executable talks to a GRPC service over TLS. We would like to use this library to talk to BigQuery.
(See code here: (https://github.com/tower-rs/tower-grpc/issues/59#issuecomment-524001507)

The problem stems from the fact that the webpki crate under the rustls implementations has had multiple versions yanked, leaving the developer with a really crappy choices: drop TLS for your own use so you can use BigQuery, or somehow build separate crates.

```
failed to select a version for the requirement `untrusted = "^0.5"`
  candidate versions found which didn't match: 0.7.0, 0.6.2
  location searched: crates.io index
required by package `webpki-roots v0.10.0`
    ... which is depended on by `hyper-rustls v0.6.0`
    ... which is depended on by `executable_name v0.1.0 (path/to/file)`
```

**Comment by Byron** [comment]
@kiratp Could it be that #238 fixes the issue you describe? If so, I could publish the APIs you are interested in specifically.

**Comment by cswinter** [comment]
I have also run into @kiratp's issue. The https://github.com/MindFlavor/AzureSDKForRust crate depends on a recent version of `hyper-rustls` which conflicts with `hyper-rustls 0.6` or any other `hyper-rustls` version that can be used to create a `hyper::Client` for `hyper=0.10`. From what I can tell, this makes it impossible to use both the azure_sdk and google-storage1 in the same Rust project. Maybe there is some advanced build script hackery that can make this work or a way to use google-storage1 without `hyper-rustls=0.6` but so far the solution eludes me.
Now that hyper/tokio etc. have all migrated to the new stable `std::Future`, maybe it could be worth to revisit upgrading those dependencies?

**Comment by kiratp** [comment]
Apologies for the radio silence - got pulled in a different direction.

@Byron - Any guidance on how to go about testing #238 ? Maybe I'm not fully get what's going on but my interpretation of the compiler error is that our other dependancies that use rustls (https://github.com/hyperium/tonic) and this crate conflict on multiple older crates.

Since my last report, the conflict seems to have moved...
`
Error: failed to select a version for the requirement `untrusted = "^0.5"`
  candidate versions found which didn't match: 0.7.0, 0.6.2
  location searched: crates.io index
required by package `webpki-roots v0.10.0`
    ... which is depended on by `hyper-rustls v0.6.0`
    ... which is depended on by `executable_name v0.1.0 (path/to/executable)`
`

**Comment by Byron** [comment]
I agree that now would be the time to upgrade to more recent versions of `yup-oauth2` and `hyper`, and it will require some work. In theory, it should all come together once `yup-oauth2` is set to v3, working on fixing compile errors one by one.

My suggestion is to make changes to the `mako` files, and rebuild the groups-migration API to see what fails. This should be the most straight-forward way of getting where we want to be.

Right now I can't make myself work on this project, but believe it's reasonably straigforward to get started on it in case someone wants to give it a try.

Alternatively, you might want to have a look at the incubating [successor](https://github.com/google-apis-rs/generator) of these crates.

**Comment by Byron** [comment]
This is done with the latest version of the crates: v2.0.

**Comment by deven96** [comment]
The docs still shows that old hyper is intentionally used, can that be disregarded?

**Comment by Byron** [comment]
Could you provide a link or screenshot of these docs so they can be fixed? It [seems alright on crates.io](https://crates.io/crates/google-drive3/2.0.4+20210322/dependencies). Thanks

**Comment by deven96** [comment]
> Could you provide a link or screenshot of these docs so they can be fixed? It [seems alright on crates.io](https://crates.io/crates/google-drive3/2.0.4+20210322/dependencies). Thanks

Here at the [google-storage1](https://crates.io/crates/google-storage1) crate

**Comment by Byron** [comment]
Now I see, thanks! I have removed this passage and next time the crates get published the fix will become visible.

**Comment by deven96** [comment]
This means a later version of hyper can be used right?

Awesome repo @Byron

**Comment by Byron** [comment]
Hyper 0.25 is the most recent one. I merely removed a comment which by now was incorrect.

**Comment by deven96** [comment]
Requirements still show ^0.14. That shouldn't be a problem though right?

**Comment by Byron** [comment]
No, this is explicitly stating to only update to compatible versions, which is the default for `cargo` anyway.

**Comment by fosskers** [comment]
> Hyper 0.25 is the most recent one.

Confused by this... the most recent version of Hyper is `0.14.8`...

**Comment by Byron** [comment]
Thanks for the correction, I don't know where that `hyper-0.25` is coming from.
